cart/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name='cart'
urlpatterns = [
    path('',views.product_list,	name='product_list'),
	path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
	path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
    
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cartsession/urls.py
from django.urls	import	path
from . import	views
app_name	=	'cartsession'
urlpatterns	=	[
    path('',	views.cart_detail,	name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('clear/',views.clear,name='clear'),
]

orders/urls.py
from	django.urls	import	path
from	.	import	views
app_name	=	'orders'
urlpatterns	=	[
		path('create/',	views.order_create,	name='order_create'),
        
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cartsession/',	include('cartsession.urls',	namespace='cartsession')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',	include('orders.urls',	namespace='orders')),
   
    
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.urls import	reverse
# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    def	get_absolute_url(self):
        return	reverse('cart:product_list_by_category',args=[self.slug])
class product(models.Model):
    category=models.ForeignKey(category,related_name='products',on_delete=models.CASCADE)
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description	=models.TextField(blank=True)
    price	=	models.DecimalField(max_digits=10,	decimal_places=2)
    available	=	models.BooleanField(default=True)
    created	=	models.DateTimeField(auto_now_add=True)
    updated	=	models.DateTimeField(auto_now=True)

    class	Meta:
        ordering=('name',)
        index_together=(('id',	'slug'),)
    def	__str__(self):
        return	self.name
    def	get_absolute_url(self):
        return	reverse('cart:product_detail',args=[self.id,self.slug])

cartsession/models.py
from django.db import models

# Create your models here.

orders/models.py
from	django.db	import	models
from	cart.models	import	product
class Order(models.Model):
        first_name	=	models.CharField(max_length=50)
        last_name	=	models.CharField(max_length=50)
        email	=	models.EmailField()
        address	=	models.CharField(max_length=250)
        postal_code	=	models.CharField(max_length=20)
        city	=	models.CharField(max_length=100)
        created	=	models.DateTimeField(auto_now_add=True)
        updated	=	models.DateTimeField(auto_now=True)
        paid	=	models.BooleanField(default=False)
        class	Meta:
            ordering	=	('-created',)
        def	__str__(self):
            return	'Order	{}'.format(self.id)
        def	get_total_cost(self):
            return	sum(item.get_cost()	for	item	in	self.items.all())
class	OrderItem(models.Model):
        order	=	models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
        product	=	models.ForeignKey(product,related_name='order_items',on_delete=models.CASCADE)
        price	=	models.DecimalField(max_digits=10,	decimal_places=2)
        quantity	=	models.PositiveIntegerField(default=1)
        def	__str__(self):
            return	'{}'.format(self.id)
        def	get_cost(self):
            return	self.price	*	self.quantity

cartsession/forms.py
from	django	import	forms
PRODUCT_QUANTITY_CHOICES	=	[(i,	str(i))	for	i	in	range(1,	21)]
class	CartAddProductForm(forms.Form):
		quantity	=	forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
		update	=	forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

orders/forms.py
from	django	import	forms
from	.models	import	Order
class	OrderCreateForm(forms.ModelForm):
		class	Meta:
			model	=	Order
			fields	=	['first_name','last_name','email','address','postal_code','city']

cart/views.py
from django.shortcuts import render,	get_object_or_404
from	.models	import	category,	product
from cartsession.forms import CartAddProductForm
def	product_list(request,	category_slug=None):
        product_category=None
        categories=category.objects.all()
        products=product.objects.filter(available=True)
        if	category_slug:
            product_category=get_object_or_404(categories,slug=category_slug)
            products=products.filter(category=category)
        return render(request,'list.html',{'category':	product_category,'categories':	categories,'products':products})
def	product_detail(request,	id,	slug):
    
    product_info	=	get_object_or_404(product,id=id,slug=slug,available=True)
    cart_product_form=CartAddProductForm()
    return	render(request,'detail.html',{'product':product_info,'cart_product_form':cart_product_form})        

cartsession/views.py
from	django.shortcuts	import	render,	redirect,	get_object_or_404
from	django.views.decorators.http	import	require_POST
from	cart.models	import	product
from	.cart	import	Cart
from	.forms	import	CartAddProductForm
from cart.views import product_list
def	cart_detail(request):
    cart	=	Cart(request)
    for	item	in	cart:
        item['update_quantity_form']=CartAddProductForm(initial={'quantity':	item['quantity'],'update':	True})
    
    return	render(request,	'cartdetails.html',	{'cart':	cart})

@require_POST
def	cart_add(request,	product_id):
        cart	=	Cart(request)
        Product	=	get_object_or_404(product,	id=product_id)
        form	=	CartAddProductForm(request.POST)
        if	form.is_valid():
            cd	=	form.cleaned_data
            cart.add(product=Product,quantity=cd['quantity'],update_quantity=cd['update'])
        return	redirect('cartsession:cart_detail')
def	cart_remove(request,	product_id):
                cart	=	Cart(request)
                Product	=	get_object_or_404(product,	id=product_id)
                cart.remove(Product)
                return	redirect('cartsession:cart_detail')
def clear(request):
    cart=Cart(request)
    cart.clear()
    return redirect('cart:product_list')

orders/views.py
from	django.shortcuts	import	render
from	.models	import	OrderItem
from	.forms	import	OrderCreateForm
from	cartsession.cart	import	Cart

def	order_create(request):
    cart	=	Cart(request)
    if	request.method	==	'POST':
        form	=	OrderCreateForm(request.POST)
        if	form.is_valid():
            order=form.save()
            for	item	in	cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
                cart.clear()
            return	render(request,'created.html',{'order':	order})
    else:
            form	=	OrderCreateForm()
            return	render(request,'create.html',{'cart':	cart,	'form':	form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title>  {% block title %} {% endblock %}</title>
    
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{%static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{%static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{%static 'css/animate.css" rel="stylesheet">
	<link href="{%static 'css/main.css' %}" rel="stylesheet">
	<link href="{%static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							
								{%	with	total_items=cart|length	%}
      {%	if	cart|length	>	0	%}
          Your	cart:	
          <a	href="{%	url	'cartsession:cart_detail'	%}">
              {{	total_items	}}	item{{	total_items|pluralize	}},
              ${{	cart.get_total_price	}}
          </a>
          <a href="{% url 'cartsession:clear' %}">clear cart</a>
      {%	else	%}
          Your	cart	is	empty.
      {%	endif	%}
  {%	endwith	%}
							
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-md-4 clearfix">
						<div class="logo pull-left">
							<a href="#"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
						</div>
						
					</div>
					<div class="col-md-8 clearfix">
						<div class="shop-menu clearfix pull-right">
							<ul class="nav navbar-nav">
								
								<li><a href="{%	url	'cartsession:cart_detail'	%}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="/cart" class="active">Home</a></li>
								
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-sidebar">
					<h2>Category</h2>
					<div class="panel-group category-products" id="accordian"><!--category-productsr-->
						<div class="panel panel-default">
							
							
						</div>
						{% for c in categories %}
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title"><a href="#">{{c.name}}</a></h4>
							</div>
						</div>
						{% endfor %}
						
					</div><!--/category-products-->
				
					<div class="brands_products"><!--brands_products-->
						<h2>Brands</h2>
						<div class="brands-name">
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#"> Acne</a></li>
								<li><a href="#"> Grüne Erde</a></li>
								<li><a href="#"> Albiro</a></li>
								<li><a href="#"> Ronhill</a></li>
								<li><a href="#"> Oddmolly</a></li>
								<li><a href="#"> Boudestijn</a></li>
								<li><a href="#"> Rösch creative culture</a></li>
							</ul>
						</div>
					</div><!--/brands_products-->
					
					<div class="price-range"><!--price-range-->
						<h2>Price Range</h2>
						<div class="well text-center">
							 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
							 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
						</div>
					</div><!--/price-range-->
					
					<div class="shipping text-center"><!--shipping-->
						<img src="images/home/shipping.jpg" alt="" />
					</div><!--/shipping-->
				
				</div>
			</div>
	
	{% block body %}
	
	{% endblock %} 
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe3.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png' %}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" >Ashish Jain</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

  
    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/cartdetails.html
{%extends "cartbase.html" %}
{% load static %}
<html>
<head>       
{%block	title%}
		Your	shopping	cart
{%endblock%}
</head>
<body>
{% block body %}
<section id="cart_items">
        <div class="container">
                <div class="breadcrumbs">
                        <ol class="breadcrumb">
                          <li><a href="/cart">Home</a></li>
                          <li class="active">Shopping Cart</li>
                        </ol>
                </div>
                <div class="table-responsive cart_info">
                        <table class="table table-condensed">
                                <thead>
                                        <tr class="cart_menu">
                                                <td class="image">Item</td>
                                                <td class="description"></td>
                                                <td class="price">Price</td>
                                                <td class="quantity">Quantity</td>
                                                <td class="total">Total</td>
                                                <td class="Remove"> Remove</td>
                                                <td></td>
                                        </tr>
                                </thead>
                                <tbody>
                                        {%	for	item	in	cart	%}
                                        {%	with	product=item.product	%} 
                                        <tr>
                                                <td class="cart_product">
                                                        <a href=""><img src="" alt=""></a>
                                                </td>
                                                <td class="cart_description">
                                                        <h4><a href="">{{product.name}}</a></h4>
                                                        
                                                </td>
                                                <td class="cart_price">
                                                        <p>{{product.price}}</p>
                                                </td>
                                                <td class="cart_quantity">
                                                       
                                                        <form	action="{%	url	'cartsession:cart_add'	product.id	%}"	method="post">
                                                                {{	item.update_quantity_form.quantity }}
                                                                {{	item.update_quantity_form.update }}
                                                                <input	type="submit"	value="Update">
                                                                {%	csrf_token	%}
                                                </form>
                                                </td>
                                                <td class="cart_total">
                                                        <p class="cart_total_price">Rs {{item.total_price}}</p>
                                                </td>
                                                <td class="cart_delete">
                                                        <a class="cart_quantity_delete" href="{%url	'cartsession:cart_remove'	product.id	%}"><i class="fa fa-times"></i></a>
                                                </td>
                                        </tr>

                                        {% endwith %}
                                        {% endfor %}
                                </tbody>
                        </table>
                </div>
        </div>
</section> <!--/#cart_items-->

<section id="do_action">
        <div class="container">
               
                <div class="row">
                        <div class="col-sm-6">
                                
                        </div>
                        <div class="col-sm-6">
                                <div class="total_area">
                                        <ul>
                                                
                                                <li>Cart Sub Total <span>Rs {{	cart.get_total_price}}</span></li>
                                                
                                                <li>Shipping Cost <span>Free</span></li>
                                                <li>Total <span>Rs {{	cart.get_total_price}}</span></li>
                                                
                                        </ul>
                                               
                                                <a class="btn btn-default check_out" style="margin-left: 40px;" href="{% url 'orders:order_create' %}">Check Out</a>
                                </div>
                        </div>
                </div>
        </div>
</section><!--/#do_action-->


{% endblock %}




</body>
</html>

templates/create.html
{%	extends	"cartbase.html"	%}
<html>
<head>
{%	block	title	%}
    Checkout
{%	endblock	%}
</head>
<body>
{% block body %}
		<h1 style="text-align: center; font-size: 60px; font-family: cursive;"   >Checkout</h1>
		<br>
		<br>
		<div style="text-align: right;margin-right: 60px;"	class="order-info">
				<h3 style="font-family:cursive ;font-size: 40px;">Your	order</h3>
				<ul>
						{%	for	item	in	cart	%}
								<li style="font-size: 20px;">
										{{	item.quantity	}}x	{{	item.product.name	}}
										<span  >${{	item.total_price	}}</span>
								</li>
						{%	endfor	%}
				</ul>
				<p style="font-size: 20px;" >Total:	${{	cart.get_total_price	}}</p>
		</div>
		
		<form style="margin-left: 100px; border: 3px solid black;"	action="."	method="post"	class="order-form">
				{{	form.as_p	}}
				<p><input	type="submit"	value="Place order"></p>
				{%	csrf_token	%}
		</form>
		<br>
		<br>
		
{%	endblock	%}
</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        {% block title %} {{product.name}} Details {% endblock %}
    </head>
<body>
    {% block body %}
    <section>

      <div class="col-sm-9 padding-right">
        <div class="product-details"><!--product-details-->
          <div class="col-sm-5">
            <div class="view-product">
              <img src="https://source.unsplash.com/featured/?Speaker,Food,Cloths" alt="" />
              <h3>ZOOM</h3>
            </div>
          
          </div>
          <div class="col-sm-7">
            <div class="product-information"><!--/product-information-->
              <img src="{% static 'images/product-details/new.jpg' %}" class="newarrival" alt="" />
              <h2>{{product.name}}</h2>
            
              <img src="{ % sttic 'images/product-details/rating.png' %}" alt="" />
              <span>
                <span>{{product.price}}</span>
                <form	action="{%	url	"cartsession:cart_add"	product.id	%}"	method="post">
                  <br>
                  <br>
                  {{	cart_product_form	}}
                  <br>
                  <br>

                  {%	csrf_token	%}
                  <button style="margin-right: 150px;"  type="submit"	value="Add	to	cart" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Add to cart</button>
                  
              </form>

                  <i class="fa fa-shopping-cart"></i>
                  Add to cart
                </button>
              </span>
              <p><b>Availability:</b> In Stock</p>
              
              <a href=""><img src="images/product-details/share.png" class="share img-responsive"  alt="" /></a>
            </div><!--/product-information-->
          </div>
        </div><!--/product-details-->
        
        <div class="category-tab shop-details-tab"><!--category-tab-->
          <div class="col-sm-12">
            <ul class="nav nav-tabs">
              <li><a href="#details" data-toggle="tab">Details</a></li>
              
              
              <li class="active"><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
            </ul>
          </div>
          <div class="tab-content">
            <div class="tab-pane fade" id="details" >
              <div class="col-sm-3">
                {{product.description}}
            </div>
            </div>
            
            
          
            <div class="tab-pane fade active in" id="reviews" >
              <div class="col-sm-12">
                <ul>
                  <li><a href=""><i class="fa fa-user"></i>EUGEN</a></li>
                  <li><a href=""><i class="fa fa-clock-o"></i>12:41 PM</a></li>
                  <li><a href=""><i class="fa fa-calendar-o"></i>31 DEC 2014</a></li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <p><b>Write Your Review</b></p>
                
                <form action="#">
                  <span>
                    <input type="text" placeholder="Your Name"/>
                    <input type="email" placeholder="Email Address"/>
                  </span>
                  <textarea name="" ></textarea>
                  <b>Rating: </b> <img src="images/product-details/rating.png" alt="" />
                  <button type="button" class="btn btn-default pull-right">
                    Submit
                  </button>
                </form>
              </div>
            </div>
            
          </div>
        </div><!--/category-tab-->
        
        
      </div>
    </div>
  </div>
</section>

      {% endblock %}
</body>
</html>